name: GitHub Actions Demo
run-name: Testing github actions
on:
  push:
    branches: [ main ]
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      with:
          node-version: 16.x
      - run: npm audit